export const blacklist = ['?Information Security Department? User',
    'Accelops Notification',
    'Account Status',
    'Assistance I.T. Support Technician',
    'AutoCad Drafter (TEMP)',
    'Avazanga4G',
    'Broker',
    'BSEL Support',
    'Building Support',
    'Collection Agent',
    'CDMA Notification',
    'Crystal Reports',
    'Data Entry Clerk - MIND',
    'Digi Wallet Information',
    'Digital Notice',
    'Director',
    'Driver',
    'eDiscovery Manager User Account',
    'Electrical Support',
    'email account',
    'Emdia',
    'Engineering Email User',
    'FEP Project Tracking',
    'GEOTAGGER',
    'Guilio test account',
    'HR Rewards & Recognition Service Account',
    'Information Security & Data Privacy Monitoring User',
    'Infrastructure Engineer',
    'Information Security',
    'Information Security Department',
    '‎Information Security Department‎ User',
    'Intern',
    'Internet Advisory',
    'Internet Help Desk',
    'Internet Monitoring',
    'IS Support',
    'IT Service Desk',
    'Knowledge Base Admin',
    'Lava Storm Analytics',
    'MCore',
    'Monitoring User',
    'Notification user',
    'PeopleSoft Consultant',
    'Quality Analyst',
    'Quality Friends',
    'Risk Management',
    'Senior Public Relations Representative',
    'Service',
    'Service Account',
    'Shares',
    'SJC - Intern - Accounts Payable Clerk',
    'Solarwinds Management Account',
    'System Administrator',
    'Summer Student',
    'Tableu Service Account',
    'temp technical',
    'Tempoary Online Banking Confrence',
    'Test account',
    'Testing',
    'Transport Support',
    'UB Inter',
    'Webmaster'
];

export const admins = [
    'Ellen Garbutt',
    'Florentino Cal',
    'Shara Pascascio',
    'Nick Rhaburn',
    'Christopher Aguilar',
    'Keenan A. Bernard',
    'Nicole Salazar'];

export const annualNominators = [
    'Ivan Tesucum',
    'Ellen Garbutt',
    'Florentino Cal',
    'Shara Pascascio',
    'Nick Rhaburn',
    'Christopher Aguilar',
    'Keenan A. Bernard',
    'Nicole Salazar'];

export const salesNominators = [
    'Tiffany Wagner',
    'David A  Castillo',
    'Kenisha I.F.. Stuart',
    'Moshea K. Smith',
    'Dionne  Emtage',
    'Christopher Aguilar',
    'Keenan A. Bernard',
    'Nicole Salazar'];

export const creditNominators = [
    'Harriet N Flowers',
    'Marsha Haylock',
    'Ian Cleverly',
    'Christopher Aguilar',
    'Keenan A. Bernard',
    'Nicole Salazar'];